package it.polimi.ingsw.view.cli;

public enum CliCommandType {
    QUIT,
    SETNICKNAME,
    SETNUMOFPLAYERS,
    CONFIGURESTART,
    GETRESOURCESFROMMARKET,
    BUYFROMMARKET,
    GETDEVCARDCOST,
    BUYDEVCARD,
    GETPRODUCTIONCOST,
    ACTIVATEPRODUCTION,
    DISCARDLEADER,
    ACTIVATELEADER,
    MOVEBETWEENSHELF,
    MOVELEADERTOSHELF,
    MOVESHELFTOLEADER,
    SEEPLAYERBOARD,
    PRINTMYBOARD,
    ENDTURN,
    SEEOTHERSPLAYERSNAMES,
    HELP,
    HOLP
}
