package it.polimi.ingsw.view.cli;

public enum CliCommandType {
    QUIT,
    BUYFROMMARKET,
    BUYDEVCARD,
    ACTIVATEPRODUCTION,
    DISCARDLEADER,
    MOVEBETWEENSHELF,
    MOVELEADERTOSHELF,
    MOVESHELFTOLEADER,
    ACTIVATELEADER,
    ENDTURN
}
