package it.polimi.ingsw.view.cli;

public enum CliCommandType {
    QUIT,
    SETNICKNAME,
    SETNUMOFPLAYERS,
    CONFIGURESTART,
    GETRESOURCESFROMMARKET,
    BUYFROMMARKET,
    GETDEVCARDCOST,
    BUYDEVCARD,
    GETPRODUCTIONCOST,
    ACTIVATEPRODUCTION,
    DISCARDLEADER,
    MOVEBETWEENSHELF,
    MOVELEADERTOSHELF,
    MOVESHELFTOLEADER,
    ACTIVATELEADER,
    ENDTURN
}
